<?php

require_once("config.php");
include("adodb/adodb.inc.php");

$DB = NewADOConnection($db_type);
if (!$DB->Connect($db_host, $db_user, $db_pass, $db_name)) {
  print "Sorry, cannot connect to database";
  exit;
}
//$DB->debug = true;
/*
$rs = $DB->Execute("select * from user");
while (!$rs->EOF) {
  print_r($rs->fields);
  $rs->MoveNext();
}
*/

//-----------------------------------------------------------------
// executes a sql query
function db_sql($sql) {
    global $DB;
    while (!($rs = $DB->Execute($sql))) {
      handle_error("SQL: {$sql}[br]".$DB->ErrorMsg().": ".$DB->ErrorNo());
      print "SQL: {$sql}[br]".$DB->ErrorMsg().": ".$DB->ErrorNo();
      global $db_host;
      global $db_user;
      global $db_pass;
      global $db_name;
      if (!$DB->Connect($db_host, $db_user, $db_pass, $db_name)) {
        print "Sorry, cannot connect to database";
      }
      sleep(120);
    }
    return $rs;
}

//-----------------------------------------------------------------
// recursively parses an array and returns string
function parse_arr($arr, $lev) {
    if (is_array($arr)) {
        if (!isset($body)) {
            $body = "";
        }
        foreach($arr as $key => $val) {
            for ($i = 0; $i < $lev; $i++) {
                $body .= " -> ";
            }
            $body .= "$key = $val\n";
            if (is_array($val)) {
                $body .= parse_arr($val, $lev+1);
            }
        }
    }
    return $body;
}

//-----------------------------------------------------------------
// handle error of query
function handle_error($err) {
    global  $error_status;
    switch ($error_status) {
        // only print it to stdout
        case "0":
            handle_error_by_page($err);
        break;
        // compose and send error report by email to $error_email
        case "1":
            handle_error_by_email($err);
        break;
        // print it to stdout and sent email
        case "2":
            handle_error_by_email($err);
            handle_error_by_page($err);
        break;
        // ignore
        default:
        break;
    }
    return true;
}

//-----------------------------------------------------------------
function handle_error_by_page($err) {
    // vypsani hlaseni do stranky
    echo '<p>' . "\n";
    echo 'DB error:<br>'."\n";
    echo '<pre>';
    echo ereg_replace("\[br\]", "<br>", $err);
    echo '</pre></p>';
    return true;
}

//-----------------------------------------------------------------
function handle_error_by_email($err) {
    global $error_email, $db_name, $db_host, $db_user;
    $body = "hi!\ndatabase error message\ndate: ".date("d.m.Y, H:i:s", time());
/*    $body .= "\nreferer: ".(isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '(null)');
    $body .= "\nfrom: http://".$_SERVER['SERVER_NAME']."{".$_SERVER['SCRIPT_NAME']."}";
    $body .= "\nrequest method: ".$_SERVER['REQUEST_METHOD'];
    $body .= "\nuser agent: ".$_SERVER['HTTP_USER_AGENT'];
    $body .= "\nremote addr: ".$_SERVER['REMOTE_ADDR'];
    $body .= "\ndb_name: $db_name\ndb_host: $db_host\ndb_user: $db_user";
    $body .= "\nquery string: ".$_SERVER['QUERY_STRING'];
 */   $body .= "\nhttp request vars:\n";
    $body .= parse_arr($_REQUEST, 1);
    if (isset($_SESSION)) {
        $body .= "\nhttp session vars:\n";
        $body .= parse_arr($_SESSION, 1);
    }
    $body .= "\n".ereg_replace("\[br\]", "\n", $err)."\n\nmessage generated by MyDB\n\n";
    mail($error_email, "Database ERROR", $body);
    return true;
}
?>
