#!/bin/sh
#
# dvbgrab:	Starts grab and encode loop for DVBgrab
#
# chkconfig:	345 95 05
# description:	DVBgrab can store TV shows from multicast streams
#
# processname:	encode_loop,grab_loop
#

DVBGRAB_SERVICE=/var/lib/dvbgrab/dvbgrab_service
LOCKFILE=/var/lock/subsys/dvbgrab

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting DVBgrab grab loop: "
    su dvbgrab -c "$DVBGRAB_SERVICE start >/dev/null 2>&1 &"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch "$LOCKFILE"
}

stop() {
    echo -n $"Stopping DVBgrab grab loop: "
    su dvbgrab -c "$DVBGRAB_SERVICE stop" > /dev/null
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f "$LOCKFILE"
}


# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
        su dvbgrab -c "$DVBGRAB_SERVICE status"
	RETVAL=$?
        ;;
    restart)
	stop
	start
	;;
    condrestart)
        if [ -f "$LOCKFILE" ]; then
            stop
            start
        fi
        ;;
    *)
        echo $"Usage: `basename "$0"` {start|stop|status|restart|condrestart}"
        ;;
esac
exit $RETVAL
