#!/bin/sh
#
# vlc:		Starts the VideoLAN Manager daemon
#
# chkconfig:	345 95 05
# description:	The VideoLAN Manager can stream multimedia content from \
#		various sources on a network in unicast or multicast mode \
#               it's VideoLAN Client in special mode with telnet interface.
#
# processname:	vlc
# config:	/etc/videolan/vlm/vlm.cfg
#

VLCSERVER=/usr/bin/vlc
LOCKFILE=/var/lock/subsys/vlc
DVBCONF=/etc/sysconfig/dvb

# Source function library.
. /etc/rc.d/init.d/functions

# Source DVB configuration
[ -r "$DVBCONF" ] && . "$DVBCONF"

start() {
    echo -n $"Starting VideoLAN Manager: "

    echo -n $"devices "
    if [ ! -d /dev/dvb ]; then
	/sbin/MAKEDEV dvb
	RETVAL=$?
	
	[ $RETVAL -eq 0 ] || {
	    echo
	    return
	}
	
    fi
    
    chown -R vls:vls /dev/dvb
    
    echo -n $"modules "
    MODULES=`grep ^DVB_MODULE_ "$DVBCONF" | wc -l | tr -d ' '`
    for ((nr=0; nr < $MODULES; nr++)); do
    	DVB_MODULE=`eval echo '$'DVB_MODULE_$nr`
	/sbin/modprobe $DVB_MODULE &> /dev/null
	RETVAL=$?
	
	[ $RETVAL -eq 0 ] || {
	    echo
	    return
	}
    done
    source $DVBCONF
    echo -n $"daemon "
#    daemon --user vls "$VLCSERVER" -d --vlm-conf $VLM_CONFIG_FILE -I dummy 2> /dev/null
    daemon --user vls "$VLCSERVER" -d --vlm-conf $VLM_CONFIG_FILE --intf telnet --telnet-port $VLM_TELNET_PORT --telnet-password $VLM_TELNET_PASSWORD 2> /dev/null
#    daemon --user vls "$VLCSERVER" -d --logfile $VLM_LOG_FILE --file-logging --vlm-conf $VLM_CONFIG_FILE --intf telnet --telnet-port $VLM_TELNET_PORT --telnet-password $VLM_TELNET_PASSWORD 2> /dev/null
#    daemon --user vls "$VLCSERVER" -d --extraintf logger --logmode text --logfile $VLM_LOG_FILE --vlm-conf $VLM_CONFIG_FILE --intf telnet --telnet-port $VLM_TELNET_PORT --telnet-password $VLM_TELNET_PASSWORD 2> /dev/null
    RETVAL=$?
    echo
    
    [ $RETVAL -eq 0 ] && touch "$LOCKFILE"
}

stop() {
    echo -n $"Stopping VideoLAN Manager: "
    killproc `basename "$VLCSERVER"`
    RETVAL=$?
    echo
    
    [ $RETVAL -eq 0 ] && rm -f "$LOCKFILE"
}


# See how we were called.
case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
        status `basename "$VLCSERVER"`
	RETVAL=$?
        ;;
    restart)
	stop
	start
	;;
    condrestart)
	if [ -f "$LOCKFILE" ]; then
	    stop
	    start
	fi
	;;
    *)
	echo $"Usage: `basename "$0"` {start|stop|status|restart|condrestart}"
	;;
esac
exit $RETVAL
